### ISSUE TITLE
Creates PRs to drop lower bound restrictions

### ISSUE THREAD

**Issue by chriselrod** [JuliaRegistries/CompatHelper.jl#266]
For example:
https://github.com/chriselrod/StrideArrays.jl/pull/14

**Comment by davidanthoff** [comment]
Also got one of these incorrect PRs at https://github.com/julia-vscode/CSTParser.jl/pull/255. I think this should probably be fixed with high priority: if people merge these without too much care (which I've done in the past) this has the potential to really cause some chaos in the ecosystem.

**Comment by giordano** [comment]
Related to this issue, https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/1017 changed compat from
```toml
BinaryBuilderBase = "0.5"
```
to
```toml
BinaryBuilderBase = "0.5, 0.4"
```
but `BinaryBuilderBase` isn't even compatible with Julia v1.6, where CompatHelper was running when opened this PR.  I should also note that `BinaryBuilderBase` v0.5 isn't registered yet, I don't know if this is a problem for CompatHelper.

**Comment by DilumAluthge** [comment]
I think the culprit here is the Pkg server being out of date. In the v3 rewrite we will only use the Git registry (we'll drop support for Pkg server registries), so this should be fixed in v3.

**Comment by giordano** [comment]
This is still happening: https://github.com/EnzymeAD/Reactant.jl/pull/694

**Comment by giordano** [comment]
> so this should be fixed in v3.

[v3](https://github.com/JuliaRegistries/CompatHelper.jl/releases/tag/v3.0.0) happened 4 years ago now

**Comment by DilumAluthge** [comment]
Hmmm. We'll need some better logging to figure out what's going on here.

**Comment by DilumAluthge** [comment]
> This one also [fonsp/Pluto.jl#3163](https://github.com/fonsp/Pluto.jl/pull/3163), it ran after the added logging so might be useful

That's actually not this issue - you're hitting #250.

You can disable those PRs by doing e.g. `CompatHelper.main(;  bump_compat_containing_equality_specifier=false)`
